import Head from "next/head";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Homes from "../components/Homes";
import OurTeam from "../components/OurTeam";

export default function Home() {
  return (
    // className={styles.container}
    <div>
      <Head>
        <title>dEMO-web-side</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header>
          <Homes />
          <Banner />
          <OurTeam />
          <Footer />
        </Header>
      </main>
    </div>
  );
}
