import Head from "next/head";
import Banner from "../components/Banner";
import Homes from "../components/Homes";
import OurTeam from "../components/OurTeam";

export default function Home() {
  return (
    // className={styles.container}
    <div>
      <Head>
        <title>dEMO-web-side</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner />
        <Homes />
        <OurTeam />
      </main>
    </div>
  );
}
